---
- name: Instalando o pacote epel-release e mais alguns pacotes básicos do sitema para a instalacao do nginx.
  hosts: churrops
  tasks:
    - name: 
      yum: name={{ item }} update_cache=yes state=present
      with_items:
        - epel-release
        - vim
        - git
        - wget
        - curl
   tags: packages-nginx